### PR TITLE
Update Hitori Runtime

### PR DESCRIPTION
**Pull request by yakushabb**
- Update runtime to 46
- Fix appdata papercuts

### CODE REVIEW

**Comment by yakushabb** [comment]
@pwithnall I've updated Hitori runtime to 46.

**Comment by pwithnall** [comment]
I no longer have time to maintain this app, sorry.

Requested to step down as maintainer: https://github.com/flathub/org.gnome.Hitori

**Comment by yakushabb** [comment]
@barthalion I've updated Hitori runtime to 46.

**Comment by bbhtt** [comment]
bot, build

**Pull request merged**
